### ISSUE TITLE
Could not pass event ShowCaseItemSpawnEvent to ShowCaseStandalone v769

### ISSUE THREAD

**Issue by JeremyFerreira** [kellerkindt/ShowCaseStandalone#5]
Hi, 
Their is an error, for each shop.
I saw someone has the same issue and closed it but how to fix it ?
I got this when the item wants to spawn : 
```
[01:08:50 ERROR]: Could not pass event ShowCaseItemSpawnEvent to ShowCaseStandalone v769
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f950f8e-58bff62]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f950f8e-58bff62]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-58bff62]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-58bff62]
        at com.kellerkindt.scs.ShowCaseStandalone.callShowCaseEvent(ShowCaseStandalone.java:505) [ShowCaseStandalone.jar:?]
        at com.kellerkindt.scs.internals.SimpleShopHandler.show(SimpleShopHandler.java:719) [ShowCaseStandalone.jar:?]
        at com.kellerkindt.scs.internals.SimpleShopHandler.showShopsFor(SimpleShopHandler.java:415) [ShowCaseStandalone.jar:?]
        at com.kellerkindt.scs.listeners.WorldListener.<init>(WorldListener.java:40) [ShowCaseStandalone.jar:?]
        at com.kellerkindt.scs.ShowCaseStandalone.onEnable(ShowCaseStandalone.java:231) [ShowCaseStandalone.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot.jar:git-Spigot-f950f8e-58bff62]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-f950f8e-58bff62]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-f950f8e-58bff62]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot.jar:git-Spigot-f950f8e-58bff62]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot.jar:git-Spigot-f950f8e-58bff62]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot.jar:git-Spigot-f950f8e-58bff62]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot.jar:git-Spigot-f950f8e-58bff62]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot.jar:git-Spigot-f950f8e-58bff62]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-f950f8e-58bff62]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot.jar:git-Spigot-f950f8e-58bff62]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
        at com.kellerkindt.scs.internals.SimpleShopHandler.onShowCaseItemSpawnEvent(SimpleShopHandler.java:752) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-f950f8e-58bff62]
        ... 19 more
```

EDIT:

More interesting

```
Caused by: java.lang.NullPointerException
        at com.kellerkindt.scs.internals.SimpleShopHandler.onShowCaseItemSpawnEvent(SimpleShopHandler.java:752) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
```

EDIT 2:

Nevermind, I got the fix by building your project, thanks anyway

**Comment by kiritss** [comment]
Did you build the project on github to fix this?

**Comment by JeremyFerreira** [comment]
uh ? No I built it with Netbeans helping by Apache Maven, you did fix the bug tho

**Comment by kiritss** [comment]
Ah, it was rather a question since I'm having a problem with it as well. I was wondering which project you've build (one on jenkins or github).

**Comment by JeremyFerreira** [comment]
The one on Github
